#!/usr/bin/env node
'use strict';

// This is a modified version of build-indexes from smogon/pokemon-showdown-client that depends
// on its vendor/-ed sibling clone of smogon/pokemon-showdown instead of one in data/ (attempting
// to clone and sync a repository doesn't work via GitHub CI, so in order to run integration tests
// on GitHub this alternative solution is required. As a bonus, its faster and gets rid of a
// redundant clone).

const fs = require("fs");
const path = require('path');
const child_process = require("child_process");

process.stdout.write("Building smogon/pokemon-showdown... ");
child_process.execSync('npm run build', {cwd: '../vendor/pokemon-showdown'});
console.log("DONE");

const psc = path.resolve(__dirname, '../vendor/pokemon-showdown-client');

const Dex = require('../vendor/pokemon-showdown/dist/sim/dex').Dex;
const CompoundWordNames = require('../vendor/pokemon-showdown/dist/data/aliases').CompoundWordNames;
const toID = Dex.toID;
process.stdout.write("Loading gen 6 data... ");
Dex.includeData();
console.log("DONE");

function es3stringify(obj) {
	const buf = JSON.stringify(obj);
	return buf.replace(/\"([A-Za-z][A-Za-z0-9]*)\"\:/g, (fullMatch, key) => (
		['return', 'new', 'delete'].includes(key) ? fullMatch : `${key}:`
	));
}

function requireNoCache(pathSpec) {
	delete require.cache[require.resolve(pathSpec)];
	return require(pathSpec);
}

/*********************************************************
 * Build pokedex.js
 *********************************************************/

process.stdout.write("Building `data/pokedex.js`... ");

{
	const Pokedex = requireNoCache('../vendor/pokemon-showdown/dist/data/pokedex.js').Pokedex;
	for (const id in Pokedex) {
		const entry = Pokedex[id];
		if (Dex.data.FormatsData[id]) {
			// console.log('formatsentry:' + id);
			const formatsEntry = Dex.data.FormatsData[id];
			if (formatsEntry.tier) entry.tier = formatsEntry.tier;
			if (formatsEntry.isNonstandard) entry.isNonstandard = formatsEntry.isNonstandard;
			if (formatsEntry.unreleasedHidden) entry.unreleasedHidden = formatsEntry.unreleasedHidden;
		}
	}
	const buf = 'exports.BattlePokedex = ' + es3stringify(Pokedex) + ';';
	fs.writeFileSync(path.join(psc, 'play.pokemonshowdown.com/data/pokedex.js'), buf);
}

console.log("DONE");

/*********************************************************
 * Build moves.js
 *********************************************************/

process.stdout.write("Building `data/moves,items,abilities,typechart,learnsets.js`...");

{
	const Moves = requireNoCache('../vendor/pokemon-showdown/dist/data/moves.js').Moves;
	for (const id in Moves) {
		const move = Dex.moves.get(Moves[id].name);
		if (move.desc) Moves[id].desc = move.desc;
		if (move.shortDesc) Moves[id].shortDesc = move.shortDesc;
		if (move.basePowerCallback) Moves[id].basePowerCallback = true;
	}
	const buf = 'exports.BattleMovedex = ' + es3stringify(Moves) + ';';
	fs.writeFileSync(path.join(psc, 'play.pokemonshowdown.com/data/moves.js'), buf);
}

/*********************************************************
 * Build items.js
 *********************************************************/

{
	const Items = requireNoCache('../vendor/pokemon-showdown/dist/data/items.js').Items;
	for (const id in Items) {
		const move = Dex.items.get(Items[id].name);
		if (move.desc) Items[id].desc = move.desc;
		if (move.shortDesc) Items[id].shortDesc = move.shortDesc;
	}
	const buf = 'exports.BattleItems = ' + es3stringify(Items) + ';';
	fs.writeFileSync(path.join(psc, 'play.pokemonshowdown.com/data/items.js'), buf);
}

/*********************************************************
 * Build abilities.js
 *********************************************************/

{
	const Abilities = requireNoCache('../vendor/pokemon-showdown/dist/data/abilities.js').Abilities;
	for (const id in Abilities) {
		const move = Dex.abilities.get(Abilities[id].name);
		if (move.desc) Abilities[id].desc = move.desc;
		if (move.shortDesc) Abilities[id].shortDesc = move.shortDesc;
	}
	const buf = 'exports.BattleAbilities = ' + es3stringify(Abilities) + ';';
	fs.writeFileSync(path.join(psc, 'play.pokemonshowdown.com/data/abilities.js'), buf);
}

/*********************************************************
 * Build typechart.js
 *********************************************************/

{
	const TypeChart = requireNoCache('../vendor/pokemon-showdown/dist/data/typechart.js').TypeChart;
	const buf = 'exports.BattleTypeChart = ' + es3stringify(TypeChart) + ';';
	fs.writeFileSync(path.join(psc, 'play.pokemonshowdown.com/data/typechart.js'), buf);
}

/*********************************************************
 * Build aliases.js
 *********************************************************/

{
	const Aliases = requireNoCache('../vendor/pokemon-showdown/dist/data/aliases.js').Aliases;
	const buf = 'exports.BattleAliases = ' + es3stringify(Aliases) + ';';
	fs.writeFileSync(path.join(psc, 'play.pokemonshowdown.com/data/aliases.js'), buf);
}

/*********************************************************
 * Build formats-data.js
 *********************************************************/

{
	const FormatsData = requireNoCache('../vendor/pokemon-showdown/dist/data/formats-data.js').FormatsData;
	const buf = 'exports.BattleFormatsData = ' + es3stringify(FormatsData) + ';';
	fs.writeFileSync(path.join(psc, 'play.pokemonshowdown.com/data/formats-data.js'), buf);
}

/*********************************************************
 * Build formats.js
 *********************************************************/

{
	const Formats = requireNoCache('../vendor/pokemon-showdown/dist/config/formats.js').Formats;
	const buf = 'exports.Formats = ' + es3stringify(Formats) + ';';
	fs.writeFileSync(path.join(psc, 'play.pokemonshowdown.com/data/formats.js'), buf);
}

/*********************************************************
 * Build learnsets.js
 *********************************************************/

{
	const Learnsets = requireNoCache('../vendor/pokemon-showdown/dist/data/learnsets.js').Learnsets;
	const buf = 'exports.BattleLearnsets = ' + es3stringify(Learnsets) + ';';
	fs.writeFileSync(path.join(psc, 'play.pokemonshowdown.com/data/learnsets.js'), buf);
}

/*********************************************************
 * Build text.js
 *********************************************************/

{
	const textData = Dex.loadTextData();
	const Text = textData.Default;

	function assignData(id, entry) {
		for (const key in entry) {
			if (['name', 'desc', 'shortDesc'].includes(key)) continue;
			const textEntry = Text[id] || (Text[id] = {});
			if (key.startsWith('gen')) {
				for (const modKey in entry[key]) {
					if (['desc', 'shortDesc'].includes(key)) continue;
					textEntry[modKey + 'Gen' + key.charAt(3)] = entry[key][modKey];
				}
			} else {
				textEntry[key] = entry[key];
			}
		}
	}

	for (const id in textData.Moves) assignData(id, textData.Moves[id]);
	for (const id in textData.Abilities) assignData(id, textData.Abilities[id]);
	for (const id in textData.Items) assignData(id, textData.Items[id]);

	const buf = 'exports.BattleText = ' + es3stringify(Text) + ';';
	fs.writeFileSync(path.join(psc, 'play.pokemonshowdown.com/data/text.js'), buf);
}

console.log("DONE");

process.stdout.write("Building smogon/pokemon-showdown-client update... ");
// FIXME: workaround for broken update script
const babelrc = fs.readFileSync(path.join(psc, '.babelrc'), 'utf8');
try {
	const overwritten = babelrc.replace('"sourceMaps": true', '"sourceMaps": false');
	fs.writeFileSync(path.join(psc, '.babelrc'), overwritten);
	child_process.execSync('node build', {cwd: '../vendor/pokemon-showdown-client'});
} finally {
	fs.writeFileSync(path.join(psc, '.babelrc'), babelrc);
}

console.log("DONE");
